TICKERS = {
    # CAC 40
    "AI.PA":    "Air Liquide",
    "AIR.PA":   "Airbus",
    "ALO.PA":   "Alstom",
    "ATO.PA":   "Atos",
    "BN.PA":    "Danone",
    "BNP.PA":   "BNP Paribas",
    "CA.PA":    "Carrefour",
    "CAP.PA":   "Capgemini",
    "CS.PA":    "AXA",
    "DG.PA":    "Vinci",
    "DSY.PA":   "Dassault Systèmes",
    "ENGI.PA":  "Engie",
    "ERF.PA":   "Eurofins",
    "GLE.PA":   "Société Générale",
    "HO.PA":    "Thales",
    "KER.PA":   "Kering",
    "LR.PA":    "Legrand",
    "MC.PA":    "LVMH",
    "ML.PA":    "Michelin",
    "MT.AS":    "ArcelorMittal",
    "ORA.PA":   "Orange",
    "PUB.PA":   "Publicis",
    "RI.PA":    "Pernod Ricard",
    "RMS.PA":   "Hermès",
    "RNO.PA":   "Renault",
    "SAF.PA":   "Safran",
    "SAN.PA":   "Sanofi",
    "SGO.PA":   "Saint-Gobain",
    "STLAM.MI": "Stellantis",
    "SU.PA":    "Schneider Electric",
    "TEP.PA":   "Teleperformance",
    "TTE.PA":   "TotalEnergies",
    "URW.PA":   "Unibail-Rodamco",
    "VIE.PA":   "Veolia",
    "VIV.PA":   "Vivendi",
    "WLN.PA":   "Worldline",
    # US Tech
    "AAPL":  "Apple",
    "MSFT":  "Microsoft",
    "GOOGL": "Alphabet",
    "AMZN":  "Amazon",
    "TSLA":  "Tesla",
    "NVDA":  "Nvidia",
    "META":  "Meta",
    # US Finance
    "JPM": "JPMorgan Chase",
    "GS":  "Goldman Sachs",
    "BAC": "Bank of America",
}